title: Kunal Dutta
subtitle: Blog & Personal Website
description: >- # this means to ignore newlines until "baseurl:"

url: "https://kdutta9.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Contact Me
      url: /contact

# Edit these details
author_logo: profile.png
author: Kunal Dutta
author_bio: Hi, I'm Kunal, a third-year student at the University of California, Berkeley, from San Jose, CA. Currently, I am studying Computer Science and Mathematics and aspiring to work with technology as a career. I started this website to blog about project development and host my professional profile. 
author_bio2: Outside of professional and academic endeavors, I enjoy basketball, spikeball, burritos, music, and matcha lattes. Please look around the site!
author_location: California
author_website_url: "http://kdutta9.github.io"
typewrite-text: Welcome to my website.
author_email: kdutta@berkeley.edu

author_education_details:
              - college_logo: berkeley.png
                college_name: University of California, Berkeley
                college_url: https://www.berkeley.edu/
                college_degree: Computer Science
                description: Bachelor of Arts
                note: Minor in Mathematics
                time: August 2018 - May 2022
                visibility: true

author_project_details:
              - project_thumbnail: posts/security-cam.JPG
                project_title: Smart Surveillance System
                project_description: IoT Security camera that sends alerts when motion is detected.
                project_url: https://github.com/kdutta9/Smart-Surveillance
                url_title: https://github.com/kdutta9/Smart-Surveillance
                visibility: true
              - project_thumbnail: project1.png
                project_title: Base Converter
                project_description: Web application that converts numbers between base systems.
                project_url: https://base-conv.herokuapp.com/
                url_title: https://base-conv.herokuapp.com/
                visibility: true
               
author_work_experiences:
            - company_name: Prep2Prep
              company_logo: prep2prep.png
              company_url: http://www.prep2prep.com/authorarticles.aspx?StaffMemberID=315
              url_title: My Articles
              designation: Sports Journalist
              description: Reported on high school sports in the Bay Area.
              note: June 2016 - Oct 2018
              visibility: true
            - company_name: Mathnasium
              company_logo: mathnasium.png
              company_url: https://www.mathnasium.com/
              url_title: Company Site
              designation: Math Instructor
              description: Taught math to students in grades K-12.
              note: June 2017 - May 2018
              visibility: true

# social links
github_username:  kdutta9
linkedin_username: kdutta9
instagram_username: kdutta9
twitter_username: KunalDuttaCS

#for comments
disqus_shortname: kdutta9

# formspree (contact form)
formspree_email: kdutta@berkeley.edu

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-140681282-1

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
# collections:
 # - products

# Gallery
# defaults:
  # -
    # scope:
      # path: "gallery"
    # values:
      # permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
